<?php
namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Request;

class Index extends Controller
{
    public function _initialize()
    {
        //header('Access-Control-Allow-Origin: http://test.six_page.com');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        $url = "http://test.six_admin.com/index/index/test";
//        $curl = curl_init();
//
//        curl_setopt($curl, CURLOPT_URL, $url);
//
//        curl_setopt($curl, CURLOPT_RETURNTRANSFER,1);
//
//        curl_setopt($curl, CURLOPT_POST, 1);
//
//        curl_setopt($curl, CURLOPT_POSTFIELDS,['pid'=>0]);
//
//        $output = curl_exec($curl);
//
//        print_r($output);exit;

        return '<style type="text/css">*{ padding: 0; margin: 0; } .think_default_text{ padding: 4px 48px;} a{color:#2E5CD5;cursor: pointer;text-decoration: none} a:hover{text-decoration:underline; } body{ background: #fff; font-family: "Century Gothic","Microsoft yahei"; color: #333;font-size:18px} h1{ font-size: 100px; font-weight: normal; margin-bottom: 12px; } p{ line-height: 1.6em; font-size: 42px }</style><div style="padding: 24px 48px;"> <h1>:)</h1><p> ThinkPHP V5<br/><span style="font-size:30px">十年磨一剑 - 为API开发设计的高性能框架</span></p><span style="font-size:22px;">[ V5.0 版本由 <a href="http://www.qiniu.com" target="qiniu">七牛云</a> 独家赞助发布 ]</span></div><script type="text/javascript" src="https://tajs.qq.com/stats?sId=9347272" charset="UTF-8"></script><script type="text/javascript" src="https://e.topthink.com/Public/static/client.js"></script><think id="ad_bd568ce7058a1091"></think>';
    }

    /**
     * @desc 接口测试
     * @param Request $request
     * @return \think\response\Json
     */
    public function queue(Request $request)
    {

        //链接redis
        $redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);

        $arr = [];

        for($i=0;$i<10000;$i++){
            $num = rand(1,10000);

            $arr[] = $num;
        }

        //生产者数据
        $arr_chunk = array_chunk($arr, 200);

        foreach ($arr_chunk as $key => $value) {
            $redis->lpush('sms_phones',json_encode($value));
        }
    }

    public function consumer(Request $request)
    {
        //链接redis
        $redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);

        while($redis->llen('sms_phones')>0 ){
            $phones = $redis->rpop('sms_phones');

            echo "已发送手机号".$phones;
        }
    }
}
